// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzsltthkgkoatmchixqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6c2x0dGhrZ2tvYXRtY2hpeHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjYwNjUsImV4cCI6MjA3MTc0MjA2NX0.NrXL5BnL9nZ0wrw-4SMhhRQ8leDLMio6rPWKG5Vmc2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});